#! /bin/bash
set -e
PATH=/usr/bin:/bin:/usr/sbin:/sbin
test -L /usr/lib/libcppknife.so && rm -f /usr/lib/libcppknife.so
test -L /usr/local/bin/fileknife && rm -f /usr/local/bin/fileknife
test -L /usr/local/bin/textknife && rm -f /usr/local/bin/textknife
test -L /usr/local/bin/sesknife && rm -f /usr/local/bin/sesknife
test -d /usr/share/cppknife-0.6.6/basic && rmdir /usr/share/cppknife-0.6.6/basic
test -d /usr/share/cppknife-0.6.6/tools && rmdir /usr/share/cppknife-0.6.6/tools
test -d /usr/share/cppknife-0.6.6/core && rmdir /usr/share/cppknife-0.6.6/core
test -d /usr/share/cppknife-0.6.6/text && rmdir /usr/share/cppknife-0.6.6/text
test -d /usr/share/cppknife-0.6.6/net && rmdir /usr/share/cppknife-0.6.6/net
test -d /usr/share/cppknife-0.6.6 && rmdir /usr/share/cppknife-0.6.6
exit 0
