#! /bin/bash
VERBOSE=-v
test "$1" = -q && VERBOSE=
for dir in *; do
  if [ -e $dir/Doxyfile ]; then
    cd $dir
    if [ -n "$VERBOSE" ]; then
      doxygen
    else
      doxygen >/dev/null 2>&1
    fi
    cd ..
  fi
done
cp $VERBOSE -a ../doc ../../seapluspro.github.io
