#! /bin/bash
set -e
VERSION=0.6.10
BASE=/usr/share/cppknife-$VERSION
PATH=/bin:/usr/bin:/sbin:/usr/sbin
date "+%Y.%m.%d-%H:%M:%S prerm $VERSION $*" >> /tmp/cppknife-full.log
for node in dbknife geoknife; do
  test -e $BASE/$node && rm -f $BASE/$node
done
for node in dbknife fileknife geoknife sesknife textknife; do
  test -L /usr/local/bin/$node && rm -f /usr/local/bin/$node
done
exit 0
