#! /bin/bash
set -e
VERSION=X.Y.Z
BASE=/usr/share/cppknife-$VERSION
PATH=/bin:/usr/bin:/sbin:/usr/sbin
for node in dbknife geoknife; do
  test -e $BASE/$node && rm -f $BASE/$node
done
for node in dbknife fileknife geoknife sesknife textknife; do
  test -L /usr/local/bin/$node && rm -f /usr/local/bin/$node
done
exit 0
